[[redirects]]
  from = "/"
  to = "/configuration"
  status = 301
  force = true

## Redirect from old Copy Pages page to new Copy Pages page
[[redirects]]
  from = "/pages"
  to = "/pages/copy"
  status = 301
  force = true

[[redirects]]
  from = "/api/webhooks"
  to = "/.netlify/functions/webhooks"
  status = 200
  force = true

[dev]
  command = "yarn dev"
  port = 8888
  targetPort = 3000
