[[redirects]]
  from = "/"
  to = "/configuration"
  status = 301
  force = true

## Redirect from old Copy Pages page to new Copy Pages page
[[redirects]]
  from = "/pages"
  to = "/pages/copy"
  status = 301
  force = true


[dev]
  command = "yarn dev:server"
  port = 8888
  targetPort = 3000

# Branch Deploy context: all deploys that are not from
# a pull/merge request or from the Production branch
# will inherit these settings.
[context.branch-deploy]
  command = "yarn build && node server.js"
